---
version: "3.3"
services:
  cache:
    image:  redis/short-url:1.0
    build: images/redis/
    container_name: redis-short-url
    network_mode: host
    ports:
      - 6379/tcp

  prim-db:
    image:  mongodb/short-url:1.0
    build: images/mongodb/
    container_name: mongodb-short-url
    network_mode: host
    ports:
      - 27017/tcp

  sec-db:
    image:  postgres/short-url:1.0
    build: images/postgres/
    container_name: postgres-short-url
    network_mode: host
    env_file: postgres.env
    ports:
      - 5432/tcp

  web-server:
    image: nginx/short-url:1.0
    build: images/nginx/
    container_name: web-server-short-url
    network_mode: host
    ports:
      - 8080/tcp

  wep-app:
    image: node/short-url:1.0
    build: images/node/
    container_name: web-app-short-url
    network_mode: host
    ports:
      - 80/tcp

networks:
  short-url-backend:
    name: short-url-backend-network
  
